CREATE DATABASE SystemMonitor;
USE SystemMonitor;

CREATE TABLE IF NOT EXISTS MasterData(
	id BIGINT NOT NULL AUTO_INCREMENT,
	serial VARCHAR(255) NOT NULL UNIQUE,
	cpuCountLogical DECIMAL(30, 2) UNSIGNED,
	cpuCount DECIMAL(30, 2) UNSIGNED,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Monitoring(
	id BIGINT NOT NULL AUTO_INCREMENT,
	serialId BIGINT NOT NULL,
	createdAt TIMESTAMP NOT NULL,
	cpuDataUser DECIMAL(30, 2) UNSIGNED,
	cpuDataNice DECIMAL(30, 2) UNSIGNED,
	cpuDataSystem DECIMAL(30, 2) UNSIGNED,
	cpuDataIdle DECIMAL(30, 2) UNSIGNED,
	cpuDataIoWait DECIMAL(30, 2) UNSIGNED,
	cpuDataIrq DECIMAL(30, 2) UNSIGNED,
	cpuDataSoftIrq DECIMAL(30, 2) UNSIGNED,
	cpuDataSteal DECIMAL(30, 2) UNSIGNED,
	cpuDataGuest DECIMAL(30, 2) UNSIGNED,
	cpuDataGuestNice DECIMAL(30, 2) UNSIGNED,
	cpuPercentageTotal DECIMAL(30, 2) UNSIGNED,
	cpuPercentageCore1 DECIMAL(30, 2) UNSIGNED,
	cpuPercentageCore2 DECIMAL(30, 2) UNSIGNED,
	cpuPercentageCore3 DECIMAL(30, 2) UNSIGNED,
	cpuPercentageCore4 DECIMAL(30, 2) UNSIGNED,
	cpuPercentageCore5 DECIMAL(30, 2) UNSIGNED,
	cpuPercentageCore6 DECIMAL(30, 2) UNSIGNED,
	cpuPercentageCore7 DECIMAL(30, 2) UNSIGNED,
	cpuPercentageCore8 DECIMAL(30, 2) UNSIGNED,
	cpuStatsSwitches BIGINT UNSIGNED,
	cpuStatsInterrupts BIGINT UNSIGNED,
	cpuStatsSoftInterrupts BIGINT UNSIGNED,
	cpuStatsSysCalls BIGINT UNSIGNED,
	cpuFreqTotalCurrent DECIMAL(30, 2) UNSIGNED,
	cpuFreqTotalMin DECIMAL(30, 2) UNSIGNED,
	cpuFreqTotalMax DECIMAL(30, 2) UNSIGNED,
	virtualMemoryDataTotal BIGINT UNSIGNED,
	virtualMemoryDataAvailable BIGINT UNSIGNED,
	virtualMemoryDataPercent DECIMAL(30, 2) UNSIGNED,
	virtualMemoryDataUsed BIGINT UNSIGNED,
	virtualMemoryDataFree BIGINT UNSIGNED,
	virtualMemoryDataActive BIGINT UNSIGNED,
	virtualMemoryDataInactive BIGINT UNSIGNED,
	virtualMemoryDataBuffers BIGINT UNSIGNED,
	virtualMemoryDataCached BIGINT UNSIGNED,
	virtualMemoryDataShared BIGINT UNSIGNED,
	virtualMemoryDataSlab BIGINT UNSIGNED,
	swapMemoryDataTotal BIGINT UNSIGNED,
	swapMemoryDataUsed BIGINT UNSIGNED,
	swapMemoryDataFree BIGINT UNSIGNED,
	swapMemoryDataPercent DECIMAL(30, 2) UNSIGNED,
	swapMemoryDataSin BIGINT UNSIGNED,
	swapMemoryDataSout BIGINT UNSIGNED,
	diskUsageTotal BIGINT UNSIGNED,
	diskUsageUsed BIGINT UNSIGNED,
	diskUsageFree BIGINT UNSIGNED,
	diskUsagePercent DECIMAL(30, 2) UNSIGNED,
	diskIoCountersTotalReadCount BIGINT UNSIGNED,
	diskIoCountersTotalWriteCount BIGINT UNSIGNED,
	diskIoCountersTotalReadBytes BIGINT UNSIGNED,
	diskIoCountersTotalWriteBytes BIGINT UNSIGNED,
	diskIoCountersTotalReadTime BIGINT UNSIGNED,
	diskIoCountersTotalWriteTime BIGINT UNSIGNED,
	netIoCountersTotalBytesSent BIGINT UNSIGNED,
	netIoCountersTotalBytesReceived BIGINT UNSIGNED,
	netIoCountersTotalPaketsSent BIGINT UNSIGNED,
	netIoCountersTotalPaketsReceived BIGINT UNSIGNED,
	netIoCountersTotalErrIn BIGINT UNSIGNED,
	netIoCountersTotalErrOut BIGINT UNSIGNED,
	netIoCountersTotalDropIn BIGINT UNSIGNED,
	netIoCountersTotalDropOut BIGINT UNSIGNED,
	sensorTemperaturesLabel VARCHAR(255),
	sensorTemperaturesCurrent DECIMAL(30, 2) UNSIGNED,
	sensorTemperaturesHigh DECIMAL(30, 2) UNSIGNED,
	sensorTemperaturesCritical DECIMAL(30, 2) UNSIGNED,
	bootTime DECIMAL(30, 2) UNSIGNED,
	PRIMARY KEY (id)
);